name: Deploy Dev

on: workflow_dispatch

env:
  HOST_ELASTIC: ${{secrets.HOST_ELASTIC}}
  API_KEY: ${{secrets.API_KEY}}
  MAIL_HOST: ${{secrets.MAIL_HOST}}
  MAIL_SENDER: ${{secrets.MAIL_SENDER}}
  MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
  MAIL_PORT: ${{secrets.MAIL_PORT}}
  MAIL_RECIPIENT: ${{secrets.MAIL_RECIPIENT}}
  RECAPTCHA_SECRET_KEY: ${{secrets.RECAPTCHA_SECRET_KEY}}
  VIVO_URL_BASE: ${{secrets.VIVO_URL_BASE}}
  VIVO_URL_ITEM_BASE: ${{secrets.VIVO_URL_ITEM_BASE}}
  BRCRIS_HOST_BASE: ${{vars.BRCRIS_HOST_BASE}}

jobs:
  dev:
    runs-on: [self-hosted, Linux, x64, runner-iroxa]
    environment:
      name: dev
      url: 'http://codich1.ibict.br:8086/'
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          sh scripts/deploy.sh
