name: Deploy Homol

on: workflow_dispatch

env:
  HOST_ELASTIC: ${{secrets.HOST_ELASTIC}}
  API_KEY: ${{secrets.API_KEY}}
  MAIL_HOST: ${{secrets.MAIL_HOST}}
  MAIL_SENDER: ${{secrets.MAIL_SENDER}}
  MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
  MAIL_PORT: ${{secrets.MAIL_PORT}}
  MAIL_RECIPIENT: ${{secrets.MAIL_RECIPIENT}}
  RECAPTCHA_SECRET_KEY: ${{secrets.RECAPTCHA_SECRET_KEY}}
  BRCRIS_HOST_BASE: ${{vars.BRCRIS_HOST_BASE}}

jobs:
  homol:
    runs-on: [self-hosted, Linux, x64, runner-homol]
    environment:
      name: homol
      url: 'http://172.16.20.48:3000/'
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    steps:
      - uses: actions/checkout@v4
      - run: |
          sh scripts/deploy.sh
